version: '3'
services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - '8080:80'
    env_file:
      - .env
    restart: unless-stopped

  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db_script.sql:/docker-entrypoint-initdb.d/db_script.sql
    restart: unless-stopped
